// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package messageservice

import (
	"context"

	"github.com/0b0e0e7c/IM/service/message-service/pb/msgservice"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMessagesRequest  = msgservice.GetMessagesRequest
	GetMessagesResponse = msgservice.GetMessagesResponse
	Message             = msgservice.Message
	SendMessageRequest  = msgservice.SendMessageRequest
	SendMessageResponse = msgservice.SendMessageResponse

	MessageService interface {
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

func (m *defaultMessageService) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := msgservice.NewMessageServiceClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (*GetMessagesResponse, error) {
	client := msgservice.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessages(ctx, in, opts...)
}
