// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package friendclient

import (
	"context"

	"github.com/0b0e0e7c/IM/friend-service/cmd/rpc/pb/friend"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddFriendRequest   = friend.AddFriendRequest
	AddFriendResponse  = friend.AddFriendResponse
	GetFriendsRequest  = friend.GetFriendsRequest
	GetFriendsResponse = friend.GetFriendsResponse

	Friend interface {
		AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error)
		GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error)
	}

	defaultFriend struct {
		cli zrpc.Client
	}
)

func NewFriend(cli zrpc.Client) Friend {
	return &defaultFriend{
		cli: cli,
	}
}

func (m *defaultFriend) AddFriend(ctx context.Context, in *AddFriendRequest, opts ...grpc.CallOption) (*AddFriendResponse, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.AddFriend(ctx, in, opts...)
}

func (m *defaultFriend) GetFriends(ctx context.Context, in *GetFriendsRequest, opts ...grpc.CallOption) (*GetFriendsResponse, error) {
	client := friend.NewFriendClient(m.cli.Conn())
	return client.GetFriends(ctx, in, opts...)
}
