// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package server

import (
	"context"

	"github.com/0b0e0e7c/IM/service/friend-service/internal/logic"
	"github.com/0b0e0e7c/IM/service/friend-service/internal/svc"
	"github.com/0b0e0e7c/IM/service/friend-service/pb/friend"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServiceServer) AddFriend(ctx context.Context, in *friend.AddFriendRequest) (*friend.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *FriendServiceServer) GetFriends(ctx context.Context, in *friend.GetFriendsRequest) (*friend.GetFriendsResponse, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}
