// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"github.com/0b0e0e7c/chat/service/message-service/internal/logic"
	"github.com/0b0e0e7c/chat/service/message-service/internal/svc"
	"github.com/0b0e0e7c/chat/service/message-service/pb/message"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	message.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SendMessage(ctx context.Context, in *message.SendMessageRequest) (*message.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageServiceServer) GetMessages(ctx context.Context, in *message.GetMessagesRequest) (*message.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}
