// Code generated by goctl. DO NOT EDIT.
// Source: msg.proto

package server

import (
	"context"

	"github.com/0b0e0e7c/IM/service/message-service/internal/logic"
	"github.com/0b0e0e7c/IM/service/message-service/internal/svc"
	"github.com/0b0e0e7c/IM/service/message-service/pb/msgservice"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	msgservice.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServiceServer) SendMessage(ctx context.Context, in *msgservice.SendMessageRequest) (*msgservice.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

func (s *MessageServiceServer) GetMessages(ctx context.Context, in *msgservice.GetMessagesRequest) (*msgservice.GetMessagesResponse, error) {
	l := logic.NewGetMessagesLogic(ctx, s.svcCtx)
	return l.GetMessages(in)
}
