// Code generated by goctl. DO NOT EDIT.
package types

type UserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type UserResponse struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
}
