// Code generated by goctl. DO NOT EDIT.
// Source: friend.proto

package server

import (
	"context"

	"github.com/0b0e0e7c/IM/friend-service/cmd/rpc/internal/logic"
	"github.com/0b0e0e7c/IM/friend-service/cmd/rpc/internal/svc"
	"github.com/0b0e0e7c/IM/friend-service/cmd/rpc/pb/friend"
)

type FriendServer struct {
	svcCtx *svc.ServiceContext
	friend.UnimplementedFriendServer
}

func NewFriendServer(svcCtx *svc.ServiceContext) *FriendServer {
	return &FriendServer{
		svcCtx: svcCtx,
	}
}

func (s *FriendServer) AddFriend(ctx context.Context, in *friend.AddFriendRequest) (*friend.AddFriendResponse, error) {
	l := logic.NewAddFriendLogic(ctx, s.svcCtx)
	return l.AddFriend(in)
}

func (s *FriendServer) GetFriends(ctx context.Context, in *friend.GetFriendsRequest) (*friend.GetFriendsResponse, error) {
	l := logic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}
